webtalk_init -webtalk_dir /home/tansei/Desktop/186cpu/fpu/FSQRT/xsim.dir/test_fsqrt.sim/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Mon Feb 11 15:57:25 2019" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2017.4 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2086221" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "LIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "488fec07-86c7-460e-9363-4e70332449c1" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "583c0398-0d57-4dac-b4f7-499620c0884a" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "174" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Ubuntu" -context "user_environment"
webtalk_add_data -client project -key os_release -value "Ubuntu 16.04.5 LTS" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Core(TM) i7-4610M CPU @ 3.00GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "3599.882 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "16.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key runall -value "true" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key Command -value "xsim" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key runtime -value "1067427 ns" -context "xsim\\usage"
webtalk_add_data -client xsim -key iteration -value "0" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Time -value "1.01_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Memory -value "130160_KB" -context "xsim\\usage"
webtalk_transmit -clientid 947710502 -regid "" -xml /home/tansei/Desktop/186cpu/fpu/FSQRT/xsim.dir/test_fsqrt.sim/webtalk/usage_statistics_ext_xsim.xml -html /home/tansei/Desktop/186cpu/fpu/FSQRT/xsim.dir/test_fsqrt.sim/webtalk/usage_statistics_ext_xsim.html -wdm /home/tansei/Desktop/186cpu/fpu/FSQRT/xsim.dir/test_fsqrt.sim/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
